spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: 'jdbc:mysql://localhost:3307/ligacao?allowPublicKeyRetrieval=true&useSSL=false'
  jpa:
    hibernate:
      ddl-auto: update